"""add holding fields, rename snapshot open_val

Revision ID: c667a18d8e68
Revises: c8928d0df9a7
Create Date: 2026-03-25 16:15:46.169466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c667a18d8e68'
down_revision = 'c8928d0df9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coingecko_id', sa.String(length=80), nullable=True))

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_override', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))
        batch_op.alter_column('shares',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('physical_metals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_metals', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('date')
        batch_op.drop_column('form')

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('shares',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('value_override')

    with op.batch_alter_table('crypto_holdings', schema=None) as batch_op:
        batch_op.drop_column('coingecko_id')

    # ### end Alembic commands ###
