"""initial schema - 21 tables

Revision ID: c8928d0df9a7
Revises: 
Create Date: 2026-03-25 15:57:18.049386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8928d0df9a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('econ_calendar_cache',
    sa.Column('week_key', sa.String(length=10), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('week_label', sa.String(length=80), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('week_key')
    )
    op.create_table('fred_cache',
    sa.Column('series_group', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('series_group')
    )
    op.create_table('price_cache',
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('sentiment_cache',
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('verify_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('blended_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('allocations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blended_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blended_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('budget_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('rollover_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_budget_user')
    )
    with op.batch_alter_table('budget_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_configs_user_id'), ['user_id'], unique=False)

    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_rules_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_catrule_user', ['user_id'], unique=False)

    op.create_table('crypto_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crypto_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crypto_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('custom_pulse_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_pulse_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_pulse_cards_user_id'), ['user_id'], unique=False)

    op.create_table('financial_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_goals_user_id'), ['user_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('account', sa.String(length=120), nullable=True),
    sa.Column('bucket', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('monthly_investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('contributed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'category', name='uq_monthly_inv')
    )
    with op.batch_alter_table('monthly_investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_investments_user_id'), ['user_id'], unique=False)

    op.create_table('physical_metals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metal', sa.String(length=10), nullable=False),
    sa.Column('oz', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physical_metals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physical_metals_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('gold_price', sa.Float(), nullable=True),
    sa.Column('silver_price', sa.Float(), nullable=True),
    sa.Column('tnx_10y', sa.Float(), nullable=True),
    sa.Column('tnx_2y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_snapshot_user_date')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_snapshot_user_date', ['user_id', 'date'], unique=False)

    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('account', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('import_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_txn_user_date', ['user_id', 'date'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Float(), nullable=True),
    sa.Column('contribution_frequency', sa.String(length=20), nullable=True),
    sa.Column('contribution_plan', sa.JSON(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.Column('pulse_order', sa.JSON(), nullable=True),
    sa.Column('widget_order', sa.JSON(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('coinbase_key_name', sa.String(length=255), nullable=True),
    sa.Column('coinbase_private_key', sa.Text(), nullable=True),
    sa.Column('goldapi_key', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_date')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))

    op.drop_table('transactions')
    op.drop_table('subscriptions')
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_user_id'))

    op.drop_table('recurring_transactions')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_user_id'))

    op.drop_table('price_alerts')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_user_date')
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_user_id'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('physical_metals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physical_metals_user_id'))

    op.drop_table('physical_metals')
    with op.batch_alter_table('monthly_investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_investments_user_id'))

    op.drop_table('monthly_investments')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_user_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_goals_user_id'))

    op.drop_table('financial_goals')
    with op.batch_alter_table('custom_pulse_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_pulse_cards_user_id'))

    op.drop_table('custom_pulse_cards')
    with op.batch_alter_table('crypto_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crypto_holdings_user_id'))

    op.drop_table('crypto_holdings')
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_catrule_user')
        batch_op.drop_index(batch_op.f('ix_category_rules_user_id'))

    op.drop_table('category_rules')
    with op.batch_alter_table('budget_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_configs_user_id'))

    op.drop_table('budget_configs')
    with op.batch_alter_table('blended_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blended_accounts_user_id'))

    op.drop_table('blended_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sentiment_cache')
    op.drop_table('price_cache')
    op.drop_table('fred_cache')
    op.drop_table('econ_calendar_cache')
    # ### end Alembic commands ###
